# Generated by Django 4.1.5 on 2023-01-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_img')),
                ('discount_deal', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
