# Generated by Django 4.1.5 on 2023-01-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_section_product_image_product_section_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_info',
            new_name='Additional_information',
        ),
    ]
